name: Clang-12 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Initialize Pipeline Environment
      run: |
          sudo apt-get install ninja-build
          sudo apt install llvm-12 clang-12
          sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-12 100 \
            --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-12 --slave /usr/bin/llvm-cov llvm-cov \
            /usr/bin/llvm-cov-12
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ -GNinja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}     
